---
# This file includes all task groups for better organization.
# Keeping things simple and readable.

- import_tasks: updates.yml
- import_tasks: users.yml
- import_tasks: ssh.yml
- import_tasks: ufw.yml
- import_tasks: banners.yml
- import_tasks: sysctl.yml
